  
  #####
  #  Basic Methods
  #
  def add_constraint(table, foreign_key, related_table)

    query = "alter table #{table} add CONSTRAINT `#{table}_#{foreign_key}_fk` FOREIGN KEY "
    query += "(`#{foreign_key}`) REFERENCES `#{related_table}` (`id`)"

    ActiveRecord::Base.connection.execute(query)

  end


	######
	#  Structural Constraints
	#
	add_constraint("activations", "laptop_id", "laptops" )
	add_constraint("activations", "person_activated_id", "people" )
	add_constraint("answers", "person_id", "people" )
	add_constraint("answers", "quiz_id", "quizzes" )
	add_constraint("bank_deposits", "problem_solution_id", "problem_solutions" )
	add_constraint("batteries", "box_id", "boxes" )
	add_constraint("batteries", "owner_id", "people" )
	add_constraint("batteries", "shipment_arrival_id", "shipments" )
	add_constraint("batteries", "status_id", "statuses" )
	add_constraint("box_movement_details", "box_id", "boxes" )
	add_constraint("box_movement_details", "box_movement_id", "box_movements" )
	add_constraint("box_movements", "authorized_person_id", "people" )
	add_constraint("box_movements", "dst_person_id", "people" )
	add_constraint("box_movements", "dst_place_id", "places" )
	add_constraint("box_movements", "src_person_id", "people" )
	add_constraint("box_movements", "src_place_id", "places" )
	add_constraint("boxes", "place_id", "places" )
	add_constraint("boxes", "shipment_id", "shipments" )
	add_constraint("chargers", "box_id", "boxes" )
	add_constraint("chargers", "owner_id", "people" )
	add_constraint("chargers", "shipment_arrival_id", "shipments" )
	add_constraint("chargers", "status_id", "statuses" )
	add_constraint("choices", "answer_id", "answers" )
	add_constraint("choices", "option_id", "options" )
	add_constraint("choices", "question_id", "questions" )
	add_constraint("events", "place_id", "places" )
	add_constraint("laptop_details", "laptop_id", "laptops" )
	add_constraint("laptop_details", "person_id", "people" )
	add_constraint("laptop_details", "section_detail_id", "section_details" )
	add_constraint("laptops", "box_id", "boxes" )
	add_constraint("laptops", "model_id", "models" )
	add_constraint("laptops", "owner_id", "people" )
	add_constraint("laptops", "status_id", "statuses" )
	add_constraint("lots", "person_id", "people" )
	add_constraint("movement_details", "battery_id", "batteries" )
	add_constraint("movement_details", "charger_id", "chargers" )
	add_constraint("movement_details", "laptop_id", "laptops" )
	add_constraint("movement_details", "movement_id", "movements" )
	add_constraint("movements", "destination_person_id", "people" )
	add_constraint("movements", "movement_type_id", "movement_types" )
	add_constraint("movements", "responsible_person_id", "people" )
	add_constraint("movements", "source_person_id", "people" )
	add_constraint("node_types", "image_id", "images" )
	add_constraint("nodes", "node_type_id", "node_types" )
	add_constraint("nodes", "place_id", "places" )
	add_constraint("notification_subscribers", "notification_id", "notifications" )
	add_constraint("notification_subscribers", "person_id", "people" )
	add_constraint("notifications_pools", "place_id", "places" )
	add_constraint("notifications_pools", "notification_id", "notifications" )
	add_constraint("options", "question_id", "questions" )
	add_constraint("parts", "battery_id", "batteries" )
	add_constraint("parts", "charger_id", "chargers" )
	add_constraint("parts", "laptop_id", "laptops" )
	add_constraint("parts", "owner_id", "people" )
	add_constraint("parts", "part_type_id", "part_types" )
	add_constraint("parts", "status_id", "statuses" )
	add_constraint("people", "image_id", "images" )
	add_constraint("people", "place_id", "places" )
	add_constraint("performs", "person_id", "people" )
	add_constraint("performs", "place_id", "places" )
	add_constraint("performs", "profile_id", "profiles" )
	add_constraint("permissions", "controller_id", "controllers" )
	add_constraint("place_dependencies", "ancestor_id", "places" )
	add_constraint("place_dependencies", "descendant_id", "places" )
	add_constraint("places", "place_id", "places" )
	add_constraint("places", "place_type_id", "place_types" )
	add_constraint("problem_reports", "owner_id", "people" )
	add_constraint("problem_reports", "place_id", "places" )
	add_constraint("problem_solutions", "dst_part_id", "parts" )
	add_constraint("problem_solutions", "solution_type_id", "solution_types" )
	add_constraint("problem_solutions", "solved_by_person_id", "people" )
	add_constraint("problem_solutions", "src_part_id", "parts" )
	add_constraint("questions", "quiz_id", "quizzes" )
	add_constraint("quizzes", "person_id", "people" )
	add_constraint("relationships", "person_id", "people" )
	add_constraint("relationships", "profile_id", "profiles" )
	add_constraint("relationships", "to_person_id", "people" )
	add_constraint("school_infos", "place_id", "places" )
	add_constraint("section_details", "lot_id", "lots" )
	add_constraint("section_details", "place_id", "places" )
	add_constraint("solution_types", "part_type_id", "part_types" )
	add_constraint("status_changes", "battery_id", "batteries" )
	add_constraint("status_changes", "charger_id", "chargers" )
	add_constraint("status_changes", "laptop_id", "laptops" )
	add_constraint("status_changes", "new_state_id", "statuses" )
	add_constraint("status_changes", "previous_state_id", "statuses" )
	add_constraint("users", "person_id", "people" )
